name: Push to EPITECH repository

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@devel
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: 'EpitechPromo2025'
          destination-repository-name: 'B-YEP-400-TLS-4-1-indiestudio-iona.dommel-prioux'
          user-email: iona.dommel-prioux@epitech.eu
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main